### ISSUE TITLE
Caso de uso "ver usuario (admin)"

### ISSUE THREAD

**Issue by EduLostal** [VeronikaEspa/23-24-IdSw1-SDR#16]
A la hora de especificar este caso de uso, no le encuentro sentido, ya que existe la herramienta necesaria para ver un fichaje diario.
¿Alguna sugerencia?

**Comment by mmasias** [comment]
Efectivamente, verUsuario no es lo mismo que verFichajeDeUsuario.

**Comment by VeronikaEspa** [comment]
Tal cual, verFichajeDeUsuario es diferente a "ver usuario", dado que este caso de uso especifico es para ver todos los usuarios que se encuentran en nuestro aplicativo, por ello mismo solamente se hace uso en el rol Administrador.
