### ISSUE TITLE
Relacion horario-empleado.

### ISSUE THREAD

**Issue by recinosjer** [VeronikaEspa/23-24-IdSw1-SDR#4]
Mientras estábamos en la tercera iteración con @Hexcss , @VeronikaEspa se nos presentó la siguiente duda: ¿Cual es la relación entre horario y fichaje del empleado?. Hay una relación implícita o directamente no  hay relación.

**Comment by juanjoc711** [comment]
@EduLostal y yo veíamos clara la relación tampoco, entonces pensando en la situación de Clara, que lo que quiere es revisar su informe y ver si ha cumplido su horario, decidimos que el informe es el que se relaciona con el horario ya que es una ayuda para cumplirlo. Lo hemos marcado como una relación débil ya que va medianamente implícita.

**Comment by EduLostal** [comment]
@recinosjer @VeronikaEspa Revisen el código en las imagenes/modelosUML/modeloDelDominio ya que @juanjoc711 y yo las hemos actualizado también en formato SVG pero nos ha quedado diferente.
