### ISSUE TITLE
Tareas pendientes de hacer:

### ISSUE THREAD

**Issue by juanjoc711** [VeronikaEspa/23-24-IdSw1-SDR#9]
Lista de cosas a solucionar a petición de masías:
Solucionar los enlaces directos del readme principal.
Borrar de la pagina principal del proyecto 
Añadir al README de modelo del dominio despues de poner el diagrama de clases la referencia al de estados y al de objetos para que salgan todos en ese archivo.
Corregir en el modelo del dominio la entidad Trabajadores por trabajador
Modificar la relación de trabajador con lector de huellas para que sea débil con lector, y crear una relación fuerte entre trabajador y fichaje.
En trabajador quitar todos los atributos
En fichaje dejar solo el atributo fecha y hora
Arreglar diagrama de estados.
En el diagrama de objetos hay que añadir más momentos del día (momentos representativos, un fichaje de inicio uno de final, la generación de un informe).

**Comment by luciaZama** [comment]
Se acaba de corregir todo lo correspondiente al modelo de dominio.

**Comment by recinosjer** [comment]
Se corregieron las observacion gracias a @luciaZama , se cierra el issue

**Comment by Jorge85015** [comment]
Se corrigieron los enlaces del README principal y se creo un diagrama de objetos de la creacion de un informe
